### ISSUE TITLE
Keynames "space" and "return" not recognized by input registry.

### ISSUE THREAD

**Issue by seisatsu** [Driftwood2D/Driftwood#188]
Registering keynames like "up" and "left" works fine, but for some reason keybinds such as "return" and "space" just don't connect. See an example in uitest.

@pmer can you look at why this isn't working? I am a bit stumped. I suspect there is a fundamental problem with InputManager's lookup mechanism. The callbacks for the test are set up in __menu_callbacks.py in stdlib.

**Comment by pmer** [comment]
Sure thing.

**Comment by seisatsu** [comment]
I've got this one figured out actually.
