### ISSUE TITLE
InputManager's keyname() method does not work as expected.

### ISSUE THREAD

**Issue by seisatsu** [Driftwood2D/Driftwood#189]
The method generally returns a single character relating to the key, instead of the SDL keycode as intended.

**Comment by pmer** [comment]
What is an example of a key that is returned as a single character but which shouldn't be?

**Comment by seisatsu** [comment]
All of them. I had hoped it would return the keycode values beginning with SDLK_, but it only returns an ascii or unicode character. I also can't figure out what it's using for the lookup table. Put in a number, a character comes out. I still haven't found any codes that don't correspond to a character, actually.

I want it to give us back the same codes we use to define keys, but I'm not even sure SDL has a mechanism for that now.

**Comment by pmer** [comment]
I still don't understand what you're looking for, but here's the code & lookup table for `SDL_GetKeyName()` if that helps:

- https://github.com/spurious/SDL-mirror/blob/20bc7eea50ad7459d28c6e3c15e1bf2babe68fdf/src/events/SDL_keyboard.c#L943
- https://github.com/spurious/SDL-mirror/blob/20bc7eea50ad7459d28c6e3c15e1bf2babe68fdf/src/events/SDL_keyboard.c#L905
- https://github.com/spurious/SDL-mirror/blob/20bc7eea50ad7459d28c6e3c15e1bf2babe68fdf/src/events/SDL_keyboard.c#L282

**Comment by pmer** [comment]
The function clearly returns a single character string for some input values.

**Comment by pmer** [comment]
Could you describe a bit more how you are intending to use `keyname()`?

**Comment by seisatsu** [comment]
I think I'm misunderstanding some things. I'll re-purpose this for handling text input instead.
