### ISSUE TITLE
InputManager Contexts

### ISSUE THREAD

**Issue by seisatsu** [Driftwood2D/Driftwood#190]
Implement contexts for InputManager, such that each context has a separate set of registered keybinds, and they can be switched between.

Completion of stdlib menus is blocking on this issue.

**Comment by pmer** [comment]
There are a couple of things this could be but I don't want to guess. :) What is an InputManager context?

**Comment by seisatsu** [comment]
It's a key to a dictionary containing InputManager's current setup. Change the key, change the setup. So, you can switch the keybinds around. For example, menus can create a new context and then hijack the arrow keys.
