### ISSUE TITLE
When PySDL2 is not installed, error about package "sdl2" appears confusing

### ISSUE THREAD

**Issue by pmer** [Driftwood2D/Driftwood#196]
The cross-platform solution is to run:

```sh
pip3 install pysdl2
```

But the message that's printed does not clearly describe this is how to resolve the issue.

https://github.com/Driftwood2D/Driftwood/blob/5ed4b90d42a165a72bb6885b2404f151537e4a26/src/__main__.py#L52

**Comment by seisatsu** [comment]
Alright, I can add extra messages for import failures.
