### ISSUE TITLE
Allow direct property accesses on the global object

### ISSUE THREAD

**Issue by pmer** [Driftwood2D/Driftwood#198]
We can take inspiration from [the Flask "g" global object](http://flask.pocoo.org/docs/0.12/api/#flask.g) and allow direct object property accesses rather than requiring object indexing. They look like this:

```python
from flask import g

g.playerHP = 5  # No quotes needed, looks a bit more Pythonic
print(g.playerHP)
```

Here's the source code for `g`:

https://github.com/pallets/flask/blob/3b678b7927e38af1f50cfaa60e1c2fdeaf391325/flask/ctx.py#L26-L51

**Comment by seisatsu** [comment]
Solution:

```
class AttrDict(dict):
    def __init__(self, *args, **kwargs):
        super(AttrDict, self).__init__(*args, **kwargs)
        self.__dict__ = self
```

Variables can be referenced by key or by attribute.
