### ISSUE TITLE
Graphical Effects

### ISSUE THREAD

**Issue by seisatsu** [Driftwood2D/Driftwood#52]
We need to support scriptable graphical effects such as lighting, rumbling, variable transparency, and transitions.

**Comment by seisatsu** [comment]
Lighting (with variable transparency) and rumbling are done, some graphical transitions may be wanted.

**Comment by seisatsu** [comment]
To be added:
* Colored fade in/out effect for areas.
* Pulsating fade effect.

**Comment by pmer** [comment]
What's pulsating fade effect look like?

**Comment by seisatsu** [comment]
A uniform light covering the frame, with the intensity increasing and decreasing at set intervals with set deviation and set length per cycle.

**Comment by seisatsu** [comment]
This is the Stageshow library's job now.
