### ISSUE TITLE
User's Manual

### ISSUE THREAD

**Issue by seisatsu** [Driftwood2D/Driftwood#85]
Write a User's Manual containing documentation of all engine functionality. I'm considering DAUX.IO as a documentation generator.

**Comment by pmer** [comment]
Daux.io (they use title case on their GitHub) looks nice. Hurray for their adoption of [GitHub flavored markdown](http://daux.io/Features/GitHub_Flavored_Markdown)! No need to learn a new language to write docs!

**Comment by seisatsu** [comment]
This has its own repository now.
